spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  redis:
    host: redis
    port: 6379
    
notification:
  rabbitmq:
    queue: notifications.queue
    exchange: notifications.exchange
    routingKey: notifications.routing.key

security:
  oauth2:
    client:
      clientId: notification-service
      clientSecret: ${NOTIFICATION_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

server:
  port: 8000

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.piggymetrics: DEBUG